#!/bin/bash

touch header
sed -n 1p $1 >> header
sed -n 2p $1 >> header
sed -n 3p $1 >> header

sed -i -e "s/,/./g" header
sed -i -e "s/#//g" header
sed -i -e "s/\t\t\t\t\t\t\t\t\t/,/g" header
sed -i -e "s/\t\t\t\t\t\t/,/g" header
sed -i -e "s/\t\t\t\t\t/,/g" header
sed -i -e "s/\t/,/g" header
