#!/bin/bash

echo "Nombre d'argument "$#
echo "Les arguments sont "$*
echo "Le second argument est "$2
 
echo "Et le code de retour du dernier echo est "$?
cd /home/max/BatMeca/Ressources/
pwd
cp script/st.py $1/temp/
cd $1/
pwd
cp config/$2 temp/
pwd
cp data/$3 temp/
cd temp/
pwd
ls
./st.py $2 2>&1 fichier_log.log
exit 0
